ALTER TABLE "BANK"."CUSTOMER" NOCHECK CONSTRAINT CUSTOMER_FK1
GO
ALTER TABLE "BANK"."TRANSACTION" NOCHECK CONSTRAINT TRANSACTION_FK1
GO
ALTER TABLE "BANK"."ACCOUNT" NOCHECK CONSTRAINT ACCOUNT_FK1
GO
ALTER TABLE "BANK"."TRANSACTION" NOCHECK CONSTRAINT TRANSACTION_FK2
GO
