ALTER TABLE [BANK].[TRXN] NOCHECK CONSTRAINT FK__TRXN__ACCOUNT_NU__7C30464A
GO
ALTER TABLE [BANK].[CUSTOMER] NOCHECK CONSTRAINT FK__CUSTOMER__BRANCH__748F2482
GO
ALTER TABLE [BANK].[ACCOUNT] NOCHECK CONSTRAINT FK__ACCOUNT__CUSTOME__776B912D
GO
ALTER TABLE [BANK].[TRXN] NOCHECK CONSTRAINT FK__TRXN__TRXN_CODE__7D246A83
GO
