ALTER TABLE BANK.CUSTOMER WITH CHECK CHECK CONSTRAINT CUSTOMER_FK1
GO
ALTER TABLE BANK.TRANSACTION WITH CHECK CHECK CONSTRAINT TRANSACTION_FK1
GO
ALTER TABLE BANK.ACCOUNT WITH CHECK CHECK CONSTRAINT ACCOUNT_FK1
GO
ALTER TABLE BANK.TRANSACTION WITH CHECK CHECK CONSTRAINT TRANSACTION_FK2
GO
