SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE MASKED.Dim_CustomerCardLevel (
	CustomerCardLevel_Key BIGINT NOT NULL,
	Customer_Key BIGINT NOT NULL,
	CardLevel_Key INT NOT NULL,
	CardLevelEarnedDate DATETIME,
	CardLevelExpirationDate DATETIME,
	UpgradeType VARCHAR(30),
	Rec_Ins_Date DATETIME,
	Rec_Upd_Date DATETIME,
	CustomerCardNumber VARCHAR(20),
	CustomerCardScore DECIMAL(10 , 2),
	CONSTRAINT PK__Dim_Cust__F43A2A1F59982DDB PRIMARY KEY (CustomerCardLevel_Key) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = OFF, ALLOW_PAGE_LOCKS = OFF)

)
GO

CREATE TABLE MASKED.Dim_CustomerAddress (
	CustomerAddress_Key BIGINT NOT NULL,
	Customer_Key BIGINT NOT NULL,
	Address1 VARCHAR(100),
	Address2 VARCHAR(100),
	City VARCHAR(50),
	StateName VARCHAR(50),
	ZipCode VARCHAR(20),
	ZipPlusFour VARCHAR(10),
	ContactType_Key INT,
	CountryName VARCHAR(50),
	EthnicityCC_Key INT,
	Is_Active TINYINT,
	Is_Optin TINYINT,
	Is_Preferred TINYINT,
	Is_BadAddress TINYINT,
	Is_Temporary TINYINT,
	Latitude DECIMAL(9 , 6),
	Longitude DECIMAL(9 , 6),
	Rec_Ins_Date DATETIME,
	Rec_Upd_Date DATETIME,
	Is_GlobalPreference TINYINT,
	CONSTRAINT PK__Dim_Cust__BE3102A0AB1775EA PRIMARY KEY (CustomerAddress_Key) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = OFF, ALLOW_PAGE_LOCKS = OFF)

)
GO

CREATE TABLE MASKED.Dim_CustomerMerge (
	CustomerMerge_Key BIGINT NOT NULL,
	MergeFromCustomer_Key BIGINT NOT NULL,
	MergeToCustomer_Key BIGINT NOT NULL,
	Merge_Date DATETIME,
	Rec_Ins_Date DATETIME,
	Rec_Upd_Date DATETIME,
	CONSTRAINT PK__Dim_Cust__350D2E538094E404 PRIMARY KEY (CustomerMerge_Key) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = OFF, ALLOW_PAGE_LOCKS = OFF)

)
GO

CREATE TABLE MASKED.Dim_CustomerLink (
	CustomerLink_Key BIGINT NOT NULL,
	Customer_Key BIGINT NOT NULL,
	LinkedCustomer_Key BIGINT NOT NULL,
	Linked_Date DATE,
	Is_Active TINYINT,
	Rec_Ins_Date DATETIME,
	Rec_Upd_Date DATETIME,
	CONSTRAINT PK__Dim_Cust__8462451AC71BDAAA PRIMARY KEY (CustomerLink_Key) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = OFF, ALLOW_PAGE_LOCKS = OFF)

)
GO

CREATE TABLE MASKED.Dim_CustomerEmail (
	CustomerEmail_Key BIGINT NOT NULL,
	Customer_Key BIGINT NOT NULL,
	EmailAddress VARCHAR(320),
	ContactType_Key INT,
	Is_Active TINYINT,
	Is_OptIn TINYINT,
	Is_Preferred TINYINT,
	Is_BadEmail TINYINT,
	Is_Valid TINYINT,
	Rec_Ins_Date DATETIME,
	Rec_Upd_Date DATETIME,
	Is_GlobalPreference TINYINT,
	CONSTRAINT PK__Dim_Cust__A25E90D53844D48F PRIMARY KEY (CustomerEmail_Key) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = OFF, ALLOW_PAGE_LOCKS = OFF)

)
GO

CREATE TABLE MASKED.Dim_CustomerPhone (
	CustomerPhone_Key BIGINT NOT NULL,
	Customer_Key BIGINT NOT NULL,
	PhoneNumber VARCHAR(32),
	ContactType_Key INT,
	Is_Active TINYINT,
	Is_Optin TINYINT,
	Is_Preferred TINYINT,
	Is_BadPhone TINYINT,
	Is_Valid TINYINT,
	Rec_Ins_Date DATETIME,
	Rec_Upd_Date DATETIME,
	Is_GlobalPreference TINYINT,
	CONSTRAINT PK__Dim_Cust__1415AEE846F8409E PRIMARY KEY (CustomerPhone_Key) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = OFF, ALLOW_PAGE_LOCKS = OFF)

)
GO

CREATE TABLE MASKED.Dim_CustomerInterest (
	CustomerInterest_Key BIGINT NOT NULL,
	Customer_Key BIGINT NOT NULL,
	Interest_Key INT NOT NULL,
	Is_Active TINYINT NOT NULL,
	Rec_Ins_Date DATETIME,
	Rec_Upd_Date DATETIME,
	CONSTRAINT PK__Dim_Cust__3A9353710A27CF2E PRIMARY KEY (CustomerInterest_Key) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = OFF, ALLOW_PAGE_LOCKS = OFF)

)
GO

CREATE TABLE MASKED.Dim_Customer (
	Customer_Key BIGINT NOT NULL,
	Source_Key INT,
	EnrollProperty_Key INT,
	Halo_PlayerID BIGINT,
	SrcCustomerID VARCHAR(12),
	CustomerGR_Key INT,
	CustomerCardLevel_Key BIGINT,
	DominantProperty_Key INT,
	Title_Key INT,
	FirstName_Key INT,
	MiddleName VARCHAR(50),
	LastName_Key INT,
	Suffix_Key INT,
	PreferredName_Key INT,
	EnrollmentDate DATE,
	DOB DATE,
	Is_Active TINYINT,
	Is_Merged TINYINT,
	Is_Linked TINYINT,
	Gender_Key TINYINT,
	LastUpdated_Date DATETIME,
	Rec_Ins_Date DATETIME,
	Rec_Upd_Date DATETIME,
	CurrentPointBalance DECIMAL(18 , 8),
	CurrentTierCreditBalnce DECIMAL(18 , 8),
	SRCPLAYERID BIGINT,
	IS_DAP TINYINT,
	GlobalPreference_Key INT,
	Is_GoPaperless TINYINT,
	Halo_ExternalID VARCHAR(500),
	SurvivorCode CHAR(1),
	CustomerGRKeySurvivor INT,
	Is_Deceased TINYINT,
	CONSTRAINT PK__Dim_Cust__C388CF2FB3D24176 PRIMARY KEY (Customer_Key) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = OFF, ALLOW_PAGE_LOCKS = OFF)

)
GO

CREATE TABLE MASKED.Dim_CustomerExtension (
	CustomerExtension_Key BIGINT NOT NULL,
	Customer_Key BIGINT NOT NULL,
	Property_Key INT NOT NULL,
	SrcCustomerID VARCHAR(12),
	AccountType_Key INT,
	AccountStatus_Key INT,
	FirstPlayedDate DATETIME,
	LastPlayedDate DATETIME,
	Is_Hosted TINYINT,
	Distance_From_Prop DECIMAL(9 , 2),
	Rec_Ins_Date DATETIME,
	Rec_Upd_Date DATETIME,
	RegionBucket_Key INT,
	MarketBucket_Key INT,
	CustomerLocality_Key INT,
	SrcPlayerID BIGINT,
	CreditLimit DECIMAL(10 , 2) NOT NULL,
	CasinoWalletBalanceAmount DECIMAL(10 , 2),
	CasinoWalletFirstPlayDate DATETIME,
	CasinoWalletLastPlayDate DATETIME,
	CONSTRAINT PK__Dim_Cust__C58928FA2945BFBA PRIMARY KEY (CustomerExtension_Key) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = OFF, ALLOW_PAGE_LOCKS = OFF)

)
GO

CREATE TABLE MASKED.Dim_CustomerHost (
	CustomerHost_Key BIGINT NOT NULL,
	CustomerExtension_Key BIGINT NOT NULL,
	Property_Key INT NOT NULL,
	Host_Key BIGINT NOT NULL,
	Is_Active TINYINT,
	Rec_Ins_Date DATETIME,
	Rec_Upd_Date DATETIME,
	Is_Primary TINYINT,
	CONSTRAINT PK__Dim_Cust__EE54010907FD9C64 PRIMARY KEY (CustomerHost_Key) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = OFF, ALLOW_PAGE_LOCKS = OFF)

)
GO

CREATE TABLE MASKED.Dim_CustomerHostGoal (
	CustomerHostGoal_Key BIGINT NOT NULL,
	CustomerExtension_Key BIGINT NOT NULL,
	Property_Key INT NOT NULL,
	Host_Key BIGINT NOT NULL,
	Quarter_Key INT NOT NULL,
	Goal DECIMAL(10 , 2) NOT NULL,
	Is_Active TINYINT NOT NULL,
	Rec_Ins_Date DATETIME,
	Rec_Upd_Date DATETIME,
	CONSTRAINT PK__Dim_Cust__B3FEDFFB6ABD47C1 PRIMARY KEY (CustomerHostGoal_Key) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = OFF, ALLOW_PAGE_LOCKS = OFF)

)
GO

SET ANSI_PADDING OFF
GO

