ALTER TABLE [HEALTHCARE].[PATIENT_PRESCRIPTION] NOCHECK CONSTRAINT FK__PATIENT_P__PRESC__038683F8
GO
ALTER TABLE [HEALTHCARE].[PATIENT] NOCHECK CONSTRAINT FK__PATIENT__INSURANCE__0A338187
GO
ALTER TABLE [HEALTHCARE].[PATIENT_PRESCRIPTION] NOCHECK CONSTRAINT FK__PATIENT_P__PATIE__02925FBF
GO
ALTER TABLE [HEALTHCARE].[APPOINTMENT] NOCHECK CONSTRAINT FK__APPOINTME__DOCTO__0662F0A3
GO
ALTER TABLE [HEALTHCARE].[APPOINTMENT] NOCHECK CONSTRAINT FK__APPOINTME__PATIE__075714DC
GO
ALTER TABLE [HEALTHCARE].[BILL] NOCHECK CONSTRAINT FK__BILL__APPOINTMEN__0A338187
GO
