ALTER TABLE "BANK"."ACCOUNT" DROP CONSTRAINT "ACCOUNT_FK1"
GO

ALTER TABLE "BANK"."CUSTOMER" DROP CONSTRAINT "CUSTOMER_FK1"
GO

ALTER TABLE "BANK"."TRANSACTION" DROP CONSTRAINT "TRANSACTION_FK2"
GO

ALTER TABLE "BANK"."TRANSACTION" DROP CONSTRAINT "TRANSACTION_FK1"
GO

ALTER TABLE "BANK"."ACCOUNT" DROP CONSTRAINT "ACCOUNT_IX1"
GO

ALTER TABLE "BANK"."TRANSACTION_TYPE" DROP CONSTRAINT "TRANSACTION_TYPE_UC1"
GO

ALTER TABLE "BANK"."CUSTOMER" DROP CONSTRAINT "CUSTOMER_IX1"
GO

ALTER TABLE "BANK"."BRANCH" DROP CONSTRAINT "BRANCH_IX1"
GO

ALTER TABLE "BANK"."TRANSACTION_TYPE" DROP CONSTRAINT "TRANSACTION_TYPE_IX1"
GO

ALTER TABLE "BANK"."ACCOUNT" DROP CONSTRAINT "ACCOUNT_UC1"
GO

ALTER TABLE "BANK"."CUSTOMER" DROP CONSTRAINT "CUSTOMER_UC1"
GO

DROP INDEX "BANK"."TRANSACTION"."TRANSACTION_IX1"
GO

DROP TABLE "BANK"."TRANSACTION"
GO

DROP TABLE "BANK"."BRANCH"
GO

DROP TABLE "BANK"."ACCOUNT"
GO

DROP TABLE "BANK"."TRANSACTION_TYPE"
GO

DROP TABLE "BANK"."CUSTOMER"
GO

