ALTER TABLE "BANK"."BRANCH" DROP CONSTRAINT "BRANCH_UC1"
GO

ALTER TABLE "BANK"."TRANSACTION" DROP CONSTRAINT "TRANSACTION_UC1"
GO

DROP INDEX "BANK"."BRANCH"."BRANCH_IX1"
GO

DROP INDEX "BANK"."TRANSACTION_TYPE"."TRANSACTION_TYPE_IX1"
GO

DROP INDEX "BANK"."TRANSACTION"."TRANSACTION_IX1"
GO

DROP INDEX "BANK"."CUSTOMER"."CUSTOMER_IX1"
GO

DROP INDEX "BANK"."ACCOUNT"."ACCOUNT_IX1"
GO

DROP TABLE "BANK"."ACCOUNT"
GO

DROP TABLE "BANK"."BRANCH"
GO

DROP TABLE "BANK"."TRANSACTION_TYPE"
GO

DROP TABLE "BANK"."CUSTOMER"
GO

DROP TABLE "BANK"."TRANSACTION"
GO

