SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE "BANK"."ACCOUNT" (
	"ACCOUNT_NUMBER" VARCHAR(13) NOT NULL,
	"ACCOUNT_CODE" VARCHAR(12),
	"CODE_DESCRIPTION" VARCHAR(90),
	"ACCOUNT_TYPE" VARCHAR(45),
	"CUSTOMER_ID" VARCHAR(13) NOT NULL,
	"CURRENT_BALANCE" NUMERIC(8 , 2),
	CONSTRAINT "ACCOUNT_IX1" UNIQUE ("ACCOUNT_NUMBER") WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = OFF, ALLOW_PAGE_LOCKS = OFF)
,
	CONSTRAINT "ACCOUNT_UC1" PRIMARY KEY ("ACCOUNT_NUMBER") WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = OFF, ALLOW_PAGE_LOCKS = OFF)

)
GO

CREATE TABLE "BANK"."BRANCH" (
	"BRANCH_ID" VARCHAR(20) NOT NULL,
	"LOCATION" VARCHAR(70),
	"BRANCH_DETAIL" VARCHAR(30),
	"BRANCH_NAME" VARCHAR(80),
	CONSTRAINT "BRANCH_UC1" PRIMARY KEY ("BRANCH_ID") WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = OFF, ALLOW_PAGE_LOCKS = OFF)
,
	CONSTRAINT "BRANCH_IX1" UNIQUE ("BRANCH_ID") WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = OFF, ALLOW_PAGE_LOCKS = OFF)

)
GO

CREATE TABLE "BANK"."TRANSACTION_TYPE" (
	"TRANSACTION_CODE" VARCHAR(6) NOT NULL,
	"TRANSACTION_DESCRIPTION" VARCHAR(60),
	CONSTRAINT "TRANSACTION_TYPE_IX1" UNIQUE ("TRANSACTION_CODE") WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = OFF, ALLOW_PAGE_LOCKS = OFF)
,
	CONSTRAINT "TRANSACTION_TYPE_UC1" PRIMARY KEY ("TRANSACTION_CODE") WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = OFF, ALLOW_PAGE_LOCKS = OFF)

)
GO

CREATE TABLE "BANK"."CUSTOMER" (
	"CUSTOMER_ID" VARCHAR(13) NOT NULL,
	"FULL_NAME" VARCHAR(50),
	"ADDRESS" VARCHAR(60),
	"PHONE_NUMBER" VARCHAR(25),
	"EMAIL" VARCHAR(40),
	"DATE_BECAME_MEMBER" DATE,
	"BRANCH_ID" VARCHAR(20) NOT NULL,
	"SSN" VARCHAR(11),
	CONSTRAINT "CUSTOMER_UC1" PRIMARY KEY ("CUSTOMER_ID") WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = OFF, ALLOW_PAGE_LOCKS = OFF)
,
	CONSTRAINT "CUSTOMER_IX1" UNIQUE ("CUSTOMER_ID") WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = OFF, ALLOW_PAGE_LOCKS = OFF)

)
GO

CREATE TABLE "BANK"."TRANSACTION" (
	"TRANSACTION_ID" VARCHAR(14) NOT NULL,
	"ACCOUNT_NUMBER" VARCHAR(13) NOT NULL,
	"TRANSACTION_CODE" VARCHAR(6) NOT NULL,
	"TRANSACTION_DATE" DATE,
	"TRANSACTION_AMOUNT" NUMERIC(8 , 2),
	CONSTRAINT "TRANSACTION_UC1" PRIMARY KEY ("TRANSACTION_ID") WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = OFF, ALLOW_PAGE_LOCKS = OFF)

)
GO

CREATE UNIQUE INDEX "TRANSACTION_IX1" ON "BANK"."TRANSACTION" ("TRANSACTION_ID" ASC)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = OFF, ALLOW_PAGE_LOCKS = OFF)
GO

ALTER TABLE "BANK"."ACCOUNT" ADD CONSTRAINT "ACCOUNT_FK1" FOREIGN KEY ("CUSTOMER_ID")
	REFERENCES "BANK"."CUSTOMER" ("CUSTOMER_ID")
GO

ALTER TABLE "BANK"."CUSTOMER" ADD CONSTRAINT "CUSTOMER_FK1" FOREIGN KEY ("BRANCH_ID")
	REFERENCES "BANK"."BRANCH" ("BRANCH_ID")
GO

ALTER TABLE "BANK"."TRANSACTION" ADD CONSTRAINT "TRANSACTION_FK2" FOREIGN KEY ("TRANSACTION_CODE")
	REFERENCES "BANK"."TRANSACTION_TYPE" ("TRANSACTION_CODE")
GO

ALTER TABLE "BANK"."TRANSACTION" ADD CONSTRAINT "TRANSACTION_FK1" FOREIGN KEY ("ACCOUNT_NUMBER")
	REFERENCES "BANK"."ACCOUNT" ("ACCOUNT_NUMBER")
GO

SET ANSI_PADDING OFF
GO

